# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: gpimporter # Pflichtfeld
version: '1.0' # Pflichtfeld
author: Gregor Harlan
supportpage: www.redaxo.org/de/forum

page:
    title: 'translate:title' # Werte die mit "translate:" beginnen, werden anhand der Sprachdatei übersetzt. Der Addon-Präfix (hier "gpimporter_") kann weggelassen werden.
    perm: gpimporter[]
    subpages:
        main: { title: 'translate:main' }
        config: { title: 'translate:config', perm: gpimporter[config] } # config-Seite mit separaten Rechten
